name: build

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload PC DLL to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src/MiraAPI/bin/Release/netstandard2.1/MiraApi.dll
          asset_name: MiraApi-PC.dll
          asset_content_type: application/octet-stream

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: android

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Android
        run: dotnet build --configuration Release --no-restore

      - name: Upload Android DLL to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src/MiraAPI/bin/Release/netstandard2.1/MiraApi.dll
          asset_name: MiraApi-Android.dll
          asset_content_type: application/octet-stream      - uses: actions/upload-artifact@v4
        with:
          name: AllOfUs.MiraAPI.nupkg
          path: MiraAPI/bin/Release/AllOfUs.MiraAPI.*.nupkg
          
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: MiraAPI/bin/Release/net6.0/MiraAPI.dll
          
      - name: Push NuGet package
        if: github.ref_type == 'tag'
        run: |
          dotnet nuget push MiraAPI/bin/Release/AllOfUs.MiraAPI.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
