name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-pc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - name: Rename DLL for PC
        run: mv MiraAPI/bin/Release/net6.0/MiraAPI.dll MiraAPI.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI.dll
          path: MiraAPI.dll

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: android
          submodules: true
