name: CI

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [created]

jobs:
  build-pc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build (Cake)
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - name: Collect PC DLL
        run: |
          file=$(find MiraAPI/bin/Release -name "MiraAPI.dll" | head -n 1)
          echo "PC dll: $file"
          cp "$file" MiraAPI-PC.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-PC
          path: MiraAPI-PC.dll

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: android
          submodules: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build (Cake)
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - name: Collect Android DLL
        run: |
          file=$(find MiraAPI/bin/Release -name "MiraAPI.dll" | head -n 1)
          echo "Android dll: $file"
          cp "$file" MiraAPI-Android.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-Android
          path: MiraAPI-Android.dll

  publish-release:
    runs-on: ubuntu-22.04
    needs: [build-pc, build-android]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI-PC
          path: release-assets

      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI-Android
          path: release-assets

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            release-assets/MiraAPI-PC.dll
            release-assets/MiraAPI-Android.dll          verbosity: Diagnostic

      - name: Copy PC DLL
        run: cp MiraAPI/bin/Release/net6.0/MiraAPI.dll MiraAPI-PC.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-PC
          path: MiraAPI-PC.dll

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: android
          submodules: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run the Cake script (Android)
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - name: Copy Android DLL
        run: cp MiraAPI/bin/Release/net6.0/MiraAPI.dll MiraAPI-Android.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-Android
          path: MiraAPI-Android.dll

  publish-release:
    runs-on: ubuntu-22.04
    needs: [build-pc, build-android]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI-PC
          path: ./artifacts

      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI-Android
          path: ./artifacts

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            artifacts/MiraAPI-PC.dll
            artifacts/MiraAPI-Android.dll          verbosity: Diagnostic

      - name: Rename PC DLL
        run: cp MiraAPI/bin/Release/net6.0/MiraAPI.dll MiraAPI/bin/Release/net6.0/MiraAPI.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-PC
          path: MiraAPI/bin/Release/net6.0/MiraAPI.dll

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: android
          submodules: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run the Cake script (Android)
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - name: Rename Android DLL
        run: cp MiraAPI/bin/Release/net6.0/MiraAPI.dll MiraAPI/bin/Release/net6.0/MiraAPI-Android.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-Android
          path: MiraAPI/bin/Release/net6.0/MiraAPI-Android.dll

  publish-release:
    runs-on: ubuntu-22.04
    needs: [build-pc, build-android]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI-PC
          path: ./artifacts

      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI-Android
          path: ./artifacts

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            artifacts/MiraAPI.dll
            artifacts/MiraAPI-Android.dll      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI.dll
          path: MiraAPI/bin/Release/net6.0/MiraAPI.dll

  build-android:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: android

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-Android.dll
          path: MiraAPI/bin/Release/net6.0/MiraAPI.dll

  release:
    runs-on: ubuntu-22.04
    needs: [build, build-android]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI.dll
          path: artifacts

      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI-Android.dll
          path: artifacts

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/MiraAPI.dll
            artifacts/MiraAPI-Android.dll      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI.dll
          path: MiraAPI/bin/Release/net6.0/MiraAPI.dll

      - name: Find & Rename DLL for Android
        run: |
          file=$(find MiraAPI/bin/Release -name "MiraAPI.dll" | head -n 1)
          echo "Found: $file"
          cp "$file" MiraAPI-Android.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-Android.dll
          path: MiraAPI-Android.dll
          
      - uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: |
            MiraAPI/bin/Release/net6.0/MiraAPI.dll
            MiraAPI-Android.dll      - name: Rename DLL for PC
        run: mv MiraAPI/bin/Release/net6.0/MiraAPI.dll MiraAPI.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI.dll
          path: MiraAPI.dll

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: android
          submodules: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - name: Rename DLL for Android
        run: mv MiraAPI/bin/Release/net6.0/MiraAPI.dll MiraAPI-Android.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-Android.dll
          path: MiraAPI-Android.dll

  release:
    runs-on: ubuntu-22.04
    needs: [build-pc, build-android]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI.dll
      - uses: actions/download-artifact@v4
        with:
          name: MiraAPI-Android.dll

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            MiraAPI.dll
            MiraAPI-Android.dll      - name: Rename DLL for PC
        run: mv MiraAPI/bin/Release/net6.0/MiraAPI.dll MiraAPI.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI.dll
          path: MiraAPI.dll

build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: android
          submodules: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic

      - name: Find & Rename DLL for Android
        run: |
          file=$(find MiraAPI/bin/Release -name "MiraAPI.dll" | head -n 1)
          echo "Found: $file"
          cp "$file" MiraAPI-Android.dll

      - uses: actions/upload-artifact@v4
        with:
          name: MiraAPI-Android.dll
          path: MiraAPI-Android.dll
